name: Deployment AWS Lambda Function

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
        
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRETE_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: cenipa-etl
                IMAGE_TAG: latest
              run: |
                docker build -f ./docker/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

            - name: Deployment AWS Lambda Function
              run: |
                chmod +x ./automation/scripts/deployment_lambda.sh
                ./automation/scripts/deployment_lambda.sh
              shell: bash
            
            - name: Build and Deploy AWS Step Function
              run: |
                sam build --template-file ./automation/templates/step_function_template.yaml
                sam deploy --template-file ./automation/templates/step_function_template.yaml
                
                