name: Deployment AWS Lambda Function

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
        
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRETE_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Building Local Environment
              run: |
                mkdir venv
                python -m pip install --upgrade pip setuptools wheel
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
                deactivate

                cp -r venv/lib/python3.10/site-packages/. ./
                zip -r -9 "lambda_deploy.zip" . -x '*venv*' '*.git*' '*config*'

                pwd
                ls -las
                
                function_check=$(aws lambda get-function --function-name=cenipa-etl --region=us-east-1)

                if [ ${#function_check} -gt 0 ]
                then
                    echo "Updating Lambda Cenipa-ETL"
                    aws lambda update-function-code --function-name=cenipa_etl --zip-file=fileb://lambda_deploy.zip
                else
                    echo "Creating Lambda Cenipa-ETL"
                    aws lambda create-function --function-name cenipa-etl \
                    --runtime python3.10 \
                    --handler lambda_fuction.lambda_handler \
                    --role arn:aws:iam::400582553708:role/service-role/cenipa-etl-role-o11blh01 \
                    --timeout 600 \
                    --memory-size 512 \
                    --vpc-config { "SubnetIds": ["subnet-094736222d17ac479","subnet-0b2b1239195367b1a"], "SecurityGroupIds": ["sg-0ebd6e8c7c844104d"] } \
                    --environment  Variables={s3_bucket=cenipa.etl.com.br} \
                    --zip-file=fileb://lambda_deploy.zip
                fi